name: dasar_flame
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flame: ^1.20.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/assets/images/
    - assets/assets/images/ships/
    - assets/assets/images/bullets/
    - assets/assets/images/explosion/
    - assets/assets/images/items/
    - assets/assets/images/meteor/
    - assets/assets/images/parallax/
  uses-material-design: true

